### ISSUE TITLE
Show dependency tracking on CMD UI

### ISSUE THREAD

**Issue by grufe** [OSSQA-PUM/OSSQA#120]
Reqs: R4

The program should be able to tell the user which immediate imported dependency/library received low score.
Immediate dependency means which imports are actually implemented in user/SBOM code and not a further dependency of a dependency (child dependency).
An immediate dependency should be given an aggregated score from its child dependencies.

Right now the program only lists which dependecies have the lowest score in each category, even if the SBOM is not directly dependant on the dependency with the low score.

What the program should be able to do:
- [ ] Find immediate dependency from SBOM and aggregate scores from further dependencies
- [ ] For each SSF category - list immediate dependency and aggregate score.
- [ ] For each SSF category - Display to user: name and aggregate score of immediate dependency.
