### ISSUE TITLE
Create Frontend API

### ISSUE THREAD

**Issue by jakob123100** [OSSQA-PUM/OSSQA#23]
reqs R30 Programkoden skall vara modulär
The frontend API should
- [x] recieve general parameter format ( #24 & #22 )
- [ ] generate function calls with relevant parameters for the main application structure ( #25 )
- [ ] take final score from the main application structure ( #25 )
- [ ] send final score to the interface that requested the analysis. ( #24 & #22 )
