### ISSUE TITLE
Create SSF analyzer

### ISSUE THREAD

**Issue by jakob123100** [OSSQA-PUM/OSSQA#27]
R14 Programmet skall kunna analysera en SBOM utifrån minst 5 olika kategorier,
R26 En SBOM med 200 beroenden skall kunna ge färdigt resultet på under 5 timmar,
the SSFA (SSF Analyzer) should 

- [ ] take SBOM from MAS ( #25 )
- [ ] filter dependency URL 
- [ ] send all dependency URLs to CND ( #28 ) 
- [ ] recieve existing depencencies (whole object) and needed dependencies (URL) from ( #28 )
- [ ] calculate scorecards for missing dependencies
- [ ] send new depencency scorecard data to BCI ( #29 )
- [ ] send all dependency scores of SBOM to MAS ( #25 )

**Comment by jakob123100** [comment]
This is in review for the minimum minimun viable product
