### ISSUE TITLE
Create Calculator for Needed Dependencies

### ISSUE THREAD

**Issue by jakob123100** [OSSQA-PUM/OSSQA#28]
R22 Stödja effektiva sökningar baserade på kriterier som till exempel paketnamn

The CND (Calculator of Needed Depencencies) should 
- [ ] recieve wanted depencencies from SSFA ( #27 ) 
- [ ] send get request of those dependencies to BCI ( #29 )
- [ ] recieve existing dependencies from BCI ( #29 )
- [ ] calculate missing depencencies
- [ ] send existing depencency data (whole object) and  missing depencencies (URL) to SSFA ( #27 )

**Comment by jakob123100** [comment]
This is in review for the minimum minimun viable product
