### ISSUE TITLE
Create REST API

### ISSUE THREAD

**Issue by jakob123100** [OSSQA-PUM/OSSQA#30]
R21: Databasen skall kunna lagra SBOM-filer samt de resultat och slutsatser som genereras av analysen
R22: Stödja effektiva sökningar baserade på kriterier som till exempelpaketnamn
R30: Programkoden skall vara modulär

The REST API should: 

- [ ] Be able to recive http get and post request from the BCI ( #29 )
- [ ] Send responses to back to the machine that sent the request ( #29 )
- [ ] Get data from the database ( #31 )
- [ ] Post data to the database ( #31 )

**Comment by parslie** [comment]
This was done in tandem database #31
